username: testuser
computer_name: testhost
vfs_archive: /Users/aslav/Desktop/RTU_MIREA_2COURCE/КонфигУправ/for1hw/test_vfs.zip
log_file: /Users/aslav/Desktop/RTU_MIREA_2COURCE/КонфигУправ/1home/logfile.json